source 'https://cdn.cocoapods.org/'
platform :ios, '8.0'

use_frameworks!

target 'THCalendarDatePickerSwiftExample' do
	pod 'THCalendarDatePicker', :path=> './../../'
	target 'THCalendarDatePickerSwiftExampleTests' do
		inherit! :search_paths
	end
end
