source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

target 'THCalendarDatePickerExample' do
	pod 'THCalendarDatePicker', :path=> './../../THCalendarDatePicker'
	target 'THCalendarDatePickerExampleTests' do
		inherit! :search_paths
	end
end
