source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

use_frameworks!

target 'THCalendarDatePickerSwiftExample' do
	pod 'THCalendarDatePicker', :path=> './../../THCalendarDatePicker'
	target 'THCalendarDatePickerSwiftExampleTests' do
		inherit! :search_paths
	end
end
