source 'https://cdn.cocoapods.org/'
platform :ios, '8.0'

use_frameworks!

target 'THCalendarDatePickerExampleSwift' do
    pod 'THCalendarDatePicker'
    #, :path => './../THCalendarDatePicker' 
end
